/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SendReminder': EventHandler<{ assignee: string; actions: Array<{ id: string; meetingId: string; description: string; assignee: string; dueDate: string | unknown; priority: 'low' | 'medium' | 'high'; status: 'pending' | 'in_progress' | 'done' | 'overdue'; createdAt: string; completedAt: string | unknown }>; dueCount: number; overdueCount: number }, never>
    'SendConfirmation': EventHandler<{ meetingId: string; title: string; actionIds: Array<string>; actionItems: Array<{ id: string; meetingId: string; description: string; assignee: string; dueDate: string | unknown; priority: 'low' | 'medium' | 'high'; status: 'pending' | 'in_progress' | 'done' | 'overdue'; createdAt: string; completedAt: string | unknown }>; actionsCount: number }, never>
    'SaveActions': EventHandler<{ meetingId: string; title: string; extractedActions: Array<{ description: string; assignee: string; dueDate: string | unknown; priority: 'low' | 'medium' | 'high' }> }, { topic: 'actions.saved'; data: { meetingId: string; title: string; actionIds: Array<string>; actionItems: Array<{ id: string; meetingId: string; description: string; assignee: string; dueDate: string | unknown; priority: 'low' | 'medium' | 'high'; status: 'pending' | 'in_progress' | 'done' | 'overdue'; createdAt: string; completedAt: string | unknown }>; actionsCount: number } }>
    'ExtractActions': EventHandler<{ meetingId: string; title: string; transcript: string }, { topic: 'actions.extracted'; data: { meetingId: string; title: string; extractedActions: Array<{ description: string; assignee: string; dueDate: string | unknown; priority: 'low' | 'medium' | 'high' }> } }>
    'CheckReminders': CronHandler<{ topic: 'reminder.due'; data: { assignee: string; actions: Array<{ id: string; meetingId: string; description: string; assignee: string; dueDate: string | unknown; priority: 'low' | 'medium' | 'high'; status: 'pending' | 'in_progress' | 'done' | 'overdue'; createdAt: string; completedAt: string | unknown }>; dueCount: number; overdueCount: number } }>
    'UploadMeeting': ApiRouteHandler<{ title: string; transcript: string; uploadedBy?: string }, ApiResponse<201, { id: string; title: string; transcript: string; uploadedBy?: string; createdAt: string; processed: boolean }> | ApiResponse<400, { error?: string }>, { topic: 'meeting.uploaded'; data: { meetingId: string; title: string; transcript: string } }>
    'UpdateAction': ApiRouteHandler<{ status?: 'pending' | 'in_progress' | 'done' | 'overdue'; assignee?: string; dueDate?: string | unknown }, ApiResponse<200, { id: string; meetingId: string; description: string; assignee: string; dueDate: string | unknown; priority: 'low' | 'medium' | 'high'; status: 'pending' | 'in_progress' | 'done' | 'overdue'; createdAt: string; completedAt: string | unknown }> | ApiResponse<404, { error?: unknown }>, never>
    'TestReminder': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message?: string }>, { topic: 'reminder.due'; data: { assignee: string; actions: Array<{ id: string; meetingId: string; description: string; assignee: string; dueDate: string | unknown; priority: 'low' | 'medium' | 'high'; status: 'pending' | 'in_progress' | 'done' | 'overdue'; createdAt: string; completedAt: string | unknown }>; dueCount: number; overdueCount: number } }>
    'GetDashboard': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { totalMeetings: number; activeActions: number; completedActions: number; overdueActions: number; completionRate: number; priorityBreakdown: { high: number; medium: number; low: number } }>, never>
    'GetActions': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { actions: Array<{ id: string; meetingId: string; description: string; assignee: string; dueDate: string | unknown; priority: 'low' | 'medium' | 'high'; status: 'pending' | 'in_progress' | 'done' | 'overdue'; createdAt: string; completedAt: string | unknown }>; total: number }>, never>
  }
    
}