/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ExtractActions': EventHandler<{ meetingId: string; title: string; transcript: string }, never>
    'UploadMeeting': ApiRouteHandler<{ title: string; transcript: string; uploadedBy?: string }, ApiResponse<201, { id: string; title: string; transcript: string; uploadedBy?: string; createdAt: string; processed: boolean }> | ApiResponse<400, { error?: string }>, { topic: 'meeting.uploaded'; data: { meetingId: string; title: string; transcript: string } }>
  }
    
}